export const options = [
  { value: "", label: "Sélectionnez une option" },
  { value: "SERIAL_NUMBER", label: "Serial Number" },
  { value: "MANUFACTURER", label: "Manufacturer" },
  { value: "S_PRODUCT_ID", label: "S_PRODUCT_ID" },
  { value: "RAM_SIZE", label: "RAM SIZE" },
  { value: "WIFI_MAC1", label: "WiFi MAC 1" },
  { value: "WIFI_MAC2", label: "Wifi MAC 2" },
  { value: "COUNTRY_CODE", label: "COUNTRY CODE" },
  { value: "CLIENT_CERTIFICATE", label: "CLIENT CERTIFICATE" },
  { value: "S_HARDWARE_VERSION", label: "S_HARDWARE_VERSION" },
  { value: "C_HARDWARE_REVISION", label: "C_HARDWARE_REVISION" },
  { value: "PRIVATE_KEY", label: "PRIVATE_KEY" },
  { value: "CERTIFICATE", label: "CERTIFICATE" },
  { value: "DSA", label: "DSA" },
  { value: "VENDOR_INFO1", label: "VENDOR_INFO1" },
  { value: "VENDOR_INFO2", label: "VENDOR_INFO2" },
  { value: "VENDOR_INFO3", label: "VENDOR_INFO3" },
];

export const options2 = [
  { value: "", label: "Sélectionnez une option" },
  { value: "SERIAL_NUMBER", label: "Serial Number" },
  { value: "MANUFACTURER", label: "Manufacturer" },
  { value: "S_PRODUCT_ID", label: "S_PRODUCT_ID" },
  { value: "RAM_SIZE", label: "RAM SIZE" },
  { value: "WIFI_MAC1", label: "WiFi MAC 1" },
  { value: "WIFI_MAC2", label: "Wifi MAC 2" },
  { value: "COUNTRY_CODE", label: "COUNTRY CODE" },
  { value: "CLIENT_CERTIFICATE", label: "CLIENT CERTIFICATE" },
  { value: "S_HARDWARE_VERSION", label: "S_HARDWARE_VERSION" },
  { value: "C_HARDWARE_REVISION", label: "C_HARDWARE_REVISION" },
  { value: "PRIVATE_KEY", label: "PRIVATE_KEY" },
  { value: "CERTIFICATE", label: "CERTIFICATE" },
  { value: "DSA", label: "DSA" },
  { value: "VENDOR_INFO1", label: "VENDOR_INFO1" },
  { value: "VENDOR_INFO2", label: "VENDOR_INFO2" },
  { value: "VENDOR_INFO3", label: "VENDOR_INFO3" },
];
