export const options = [
  { value: "", label: "Select an Option" },
  { value: "SERIAL_NUMBER", label: "Serial Number" },
  { value: "MANUFACTURER", label: "Manufacturer" },
  { value: "S_PRODUCT_ID", label: "S_PRODUCT_ID" },
  { value: "RAM_SIZE", label: "RAM SIZE" },
  { value: "WIFI_MAC1", label: "WiFi MAC 1" },
  { value: "WIFI_MAC2", label: "Wifi MAC 2" },
  { value: "COUNTRY_CODE", label: "COUNTRY CODE" },
  { value: "CLIENT_CERTIFICATE", label: "CLIENT CERTIFICATE" },
  { value: "S_HARDWARE_VERSION", label: "S_HARDWARE_VERSION" },
  { value: "C_HARDWARE_REVISION", label: "C_HARDWARE_REVISION" },
  { value: "PRIVATE_KEY", label: "PRIVATE_KEY" },
  { value: "CERTIFICATE", label: "CERTIFICATE" },
  { value: "DSA", label: "DSA" },
  { value: "VENDOR_INFO1", label: "VENDOR_INFO1" },
  { value: "VENDOR_INFO2", label: "VENDOR_INFO2" },
  { value: "VENDOR_INFO3", label: "VENDOR_INFO3" },
  { value: "VENDOR_INFO4", label: "VENDOR_INFO4" },
  { value: "VENDOR_INFO5", label: "VENDOR_INFO5" },
  { value: "VENDOR_INFO6", label: "VENDOR_INFO6" },
  { value: "VENDOR_INFO7", label: "VENDOR_INFO7" },
  { value: "VENDOR_INFO8", label: "VENDOR_INFO8" },
  { value: "VENDOR_INFO9", label: "VENDOR_INFO9" },
  { value: "VENDOR_INFO10", label: "VENDOR_INFO10" },
  { value: "PRIVATE_KEY", label: "PRIVATE_KEY" },
  { value: "ZIGBEE_MAC1", label: "ZIGBEE_MAC1" },
  { value: "ZIGBEE_SSID1", label: "ZIGBEE_SSID1" },
];

export const options2 = [
  { value: "", label: "Select an Option" },
  { value: "SERIAL_NUMBER", label: "Serial Number" },
  { value: "MANUFACTURER", label: "Manufacturer" },
  { value: "S_PRODUCT_ID", label: "S_PRODUCT_ID" },
  { value: "RAM_SIZE", label: "RAM SIZE" },
  { value: "WIFI_MAC1", label: "WiFi MAC 1" },
  { value: "WIFI_MAC2", label: "Wifi MAC 2" },
  { value: "COUNTRY_CODE", label: "COUNTRY CODE" },
  { value: "CLIENT_CERTIFICATE", label: "CLIENT CERTIFICATE" },
  { value: "S_HARDWARE_VERSION", label: "S_HARDWARE_VERSION" },
  { value: "C_HARDWARE_REVISION", label: "C_HARDWARE_REVISION" },
  { value: "PRIVATE_KEY", label: "PRIVATE_KEY" },
  { value: "CERTIFICATE", label: "CERTIFICATE" },
  { value: "DSA", label: "DSA" },
  { value: "VENDOR_INFO1", label: "VENDOR_INFO1" },
  { value: "VENDOR_INFO2", label: "VENDOR_INFO2" },
  { value: "VENDOR_INFO3", label: "VENDOR_INFO3" },
];
